add flushable spill_register
pulp-platform/common_cells pull request #101
Opened 2020-10-06 09:14 UTC by da-gazzi

added a flushable spill_register and removed unused signals from the old spill_register.

2020-10-15 16:24 UTC, fabianschuiki requested changes

2020-10-15 16:24 UTC, fabianschuiki commented on src/spill_register.sv
>        if (!rst_ni)
How about we instantiate `spill_register_v2` here, but with the `flush_i` signal tied to `0`?

2021-02-24 13:18 UTC, da-gazzi commented
I made `spill_register` a wrapper of `spill_register_flushable` as suggested by @fabianschuiki and fixed the dependency ordering :)

2021-06-09 14:57 UTC, zarubaf commented
Closed because of minor fixes in #119

2021-06-09 14:57 UTC, closed without merging