add round-robin distributor
pulp-platform/common_cells pull request #127
Opened 2022-01-18 17:09 UTC by micprog

2022-01-20 11:59 UTC, accuminium requested changes

2022-01-20 11:59 UTC, accuminium commented on src/rr_distributor.sv
> +    parameter int unsigned IdxWidth  = (NumOut > 32'd1) ? unsigned'($clog2(NumOut)) : 32'd1,
```suggestion
    parameter int unsigned IdxWidth  = cf_math_pkg::idx_width(NumOut),
```

2022-01-20 11:59 UTC, accuminium commented on src/rr_distributor.sv
> +    parameter type         payload_t = logic [Width-1:0],
```suggestion
    parameter type         data_t = logic [Width-1:0],
```
In most modules in this repository, we simply name the *data type of the payload* `data_t`, since there is no other data type at the interface that it could be confused with

2022-01-20 11:59 UTC, accuminium commented on Bender.yml
> +  - src/rr_distributor.sv
Do not forget to add it to `src_files.yml`

2022-01-20 11:59 UTC, accuminium commented on src/rr_distributor.sv
> +            ((rr_q == idx_t'(NumOut-1)) ? '0 : rr_q + 1'b1) : rr_q;
I strongly suggest to write this as `always_comb` instead of as nested ternary statements, and add comments describing why assignments are made

2022-01-20 11:59 UTC, accuminium commented on src/rr_distributor.sv
> +                valid_o[rr_q] = valid_i;
This does not guarantee that a `valid_o` remains high once asserted until the handshake, correct? Many of our modules that work with valid/ready assume this property (borrowed from AXI handshakes), because it makes handling inputs much easier

2022-01-25 12:18 UTC, micprog commented on src/rr_distributor.sv
> +                valid_o[rr_q] = valid_i;
Doesn't it? `valid_o` will only be high if `ready_i` is high (and `valid_i` is high), meaning that whenever `valid_o` is high the handshake completes, and isn't high otherwise.

2022-01-25 18:06 UTC, accuminium commented on src/rr_distributor.sv
> +                valid_o[rr_q] = valid_i;
You are totally right, I don't remember why I asked this. :slightly_smiling_face: 

But I see another problem with this code: For the output handshake, `valid_o` depends on `ready_i`, but the rule in valid/ready handshaking is that `ready` can depend on `valid`, but not vice-versa (to prevent combinatorial loops).

2022-01-25 18:13 UTC, accuminium commented on src/rr_distributor.sv
> +            if (valid_i && one_ready) begin
Is it intentional that the counter increases in cycles when there is no handshake? Or should this condition be `valid_i && ready_i[rr_q]` (or, equivalently after the change below `valid_i && ready_o`)?

2022-01-26 08:58 UTC, micprog commented on src/rr_distributor.sv
> +            if (valid_i && one_ready) begin
@thommythomaso is this intentional?
It being intentional would make sense to me, as in this case a valid will be served within a few cycles if any subordinate is available, even if the next in the rr distribution scheme is not ready yet (e.g. stalled for 100s of cycles). With the change discussed above, this may cause deassertion of the valid signal however, which would be against the ready/valid rules. However, not implementing the change above is also against these rules. I currently don't see a clean way to implement this feature while conforming to ready/vaild handshake rules.

2022-01-26 10:12 UTC, accuminium commented on src/rr_distributor.sv
> +            if (valid_i && one_ready) begin
Indeed. I suggest we clarify what "forwards requests to individual outputs in a round robin fashion" means in conjunction with `valid`/`ready` handshaking.

If that is not possible or does not make sense, an option could be to relax to `req`/`gnt` handshaking (where `req` can be deasserted without `gnt`, but `req` must still not depend on `gnt`).

2022-01-26 16:43 UTC, accuminium commented on src/rr_distributor.sv
> +    parameter bit          StrictRR  = 1'b0,
Thanks for the clarification!

Now, is `StrictRR = 1'b0` an actual use case? Also asking @thommythomaso?

2022-01-27 09:43 UTC, micprog commented on src/rr_distributor.sv
> +    parameter bit          StrictRR  = 1'b0,
The behavior outlined by `StrictRR = 1'b0` is currently used in the HERO dma implementation as far as I know, allowing for automatic distribution of dma transfers of different lengths. This way, if many requests are issued (> number of channels) and some are extremely long, the next transfer will be issued as soon as a dma is available, instead of waiting for the next channel in line to be available.

2022-01-28 08:39 UTC, accuminium commented on src/rr_distributor.sv
> +    parameter bit          StrictRR  = 1'b0,
I understand, thanks for the explanation.

Wouldn't it make sense to *reverse* the handshake on the output interface? That is

```sv
// output stream
input  logic  [NumOut-1:0] req_data_valid_i,
output logic  [NumOut-1:0] req_data_ready_o,
output data_t [NumOut-1:0] data_o,
output idx_t               sel_o
```

Downstream modules could then request data through `req_data_valid_i` as soon as they are available, and the `rr_distributor` can select one of them and set its `data_req_ready_o`.

2026-07-01 21:08 UTC, phsauter commented
I am closing this for being inactive for a very long time. If you think there is still merit here feel free to open it again.

2026-07-01 21:08 UTC, closed without merging