Upstream changes from `snitch`
pulp-platform/common_cells pull request #144
Opened 2022-08-08 18:43 UTC by paulsc96

2022-08-09 16:11 UTC, niwis requested changes
Thanks a lot! Could you also add the files to `src_files.yml` and `common_cells.core`?

2022-08-09 16:11 UTC, niwis commented on src/addr_decode_napot.sv
> +  parameter type         idx_t     = logic [IdxWidth-1:0]
The dependent parameters be removed
```suggestion
  parameter type         rule_t    = logic
```

2022-08-09 16:11 UTC, niwis commented on src/addr_decode_napot.sv
> +    .idx_t     ( idx_t        )
Same here
```suggestion
    .Napot     ( 1            )
```

2022-08-09 19:08 UTC, paulsc96 commented on src/addr_decode_napot.sv
> +  parameter type         idx_t     = logic [IdxWidth-1:0]
Actually, this turns out to be necessary after all, since some of the IO is `idx_t` and needs the dependent parameters. But it was good to double-check ;)

2022-08-09 19:14 UTC, paulsc96 commented
> Thanks a lot! Could you also add the files to `src_files.yml` and `common_cells.core`?

done :)

2022-08-10 07:39 UTC, niwis approved these changes

2022-08-10 07:41 UTC, merged