Add stream_join_dynamic IP
pulp-platform/common_cells pull request #151
Opened 2022-08-12 07:54 UTC by colluca

This PR addresses feature request (1) from issue #150.

2022-08-12 08:35 UTC, niwis commented
@colluca thank you for this contribution! As you mention in #150, the code of `stream_join` and `stream_join_dynamic` is very similar. Would it be possible to merge them? e.g. by modifying `stream_join` to wrap `stream_join_dynamic` and setting `sel_i = '1`. Or (perhaps even better) by instantiating `stream_join` in `stream_join_dynamic` and setting `.inp_valid_i(inp_valid_i | ~sel_i)`

2022-08-12 08:43 UTC, colluca commented
> @colluca thank you for this contribution! As you mention in #150, the code of `stream_join` and `stream_join_dynamic` is very similar. Would it be possible to merge them? e.g. by modifying `stream_join` to wrap `stream_join_dynamic` and setting `sel_i = '1`. Or (perhaps even better) by instantiating `stream_join` in `stream_join_dynamic` and setting `.inp_valid_i(inp_valid_i | ~sel_i)`

Sure :) I would favour the first option, since `stream_join_dynamic` is a superset of the functionality of `stream_join`. And I believe it only makes sense to keep `stream_join` for the reduced number of ports, correct?

2022-08-12 08:50 UTC, niwis commented
The interface of `stream_join` should not change in either case. The second option would be structurally closer to the `stream_join` logic and less invasive, but I'm okay with both

2022-09-06 11:07 UTC, colluca commented
I realized there's a corner case (when the mask disables all incoming streams) that would maybe need to be handled differently. I believe the desired behavior is not to merge anything, i.e. not to forward any valid. This makes it a bit more difficult (or inefficient if not optimized by the synthesis tool) to base `stream_join_dynamic` on `stream_join` rather than the opposite.

I pushed a first proposal where I base `stream_join` on `stream_join_dynamic`, which we can of course discuss further.

2023-09-19 10:00 UTC, niwis requested changes
Thank you @colluca. If this is ready from your side, could you rebase onto master to re-run CI? Then, this should be ready to be merged.

2023-09-19 10:00 UTC, niwis commented on src_files.yml
> +    - src/stream_join_dynamic.sv
`stream_join` now depends on `stream_join_dynamic`, so the former should go to level 1 (same for `Bender.yml`)

2023-09-26 06:54 UTC, niwis approved these changes
Thanks a lot!

2023-09-26 06:54 UTC, merged