Add glitch free clock multiplexer
pulp-platform/common_cells pull request #163
Opened 2022-12-11 15:09 UTC by meggiman

Depends on https://github.com/pulp-platform/tech_cells_generic/pull/27

2022-12-12 10:42 UTC, niwis commented on Bender.yml
> +  tech_cells_generic: { git: "https://github.com/pulp-platform/tech_cells_generic.git", rev: add_clk_OR2 }
`tc_clk_or2` is now available in tech-cells-generic v0.2.11

2022-12-15 13:44 UTC, niwis requested changes
Hi @meggiman, thanks a lot for this contribution! Just a few minor questions: Could you add the new module to `README.md`, `src_files.yml` and `common_cells.core`? While you're at it, I spotted a couple of white space / alignment issues (feel free to address them as you see fit)

2022-12-15 13:44 UTC, niwis commented on src/clk_mux_glitch_free.sv
> +  parameter int unsigned NUM_SYNC_STAGES = 2,
Alignment

2022-12-15 13:44 UTC, niwis commented on src/clk_mux_glitch_free.sv
> +   input logic [SelWidth-1:0]  async_sel_i,
```suggestion
   input logic [SelWidth-1:0]   async_sel_i,
```

2022-12-15 13:44 UTC, niwis commented on src/clk_mux_glitch_free.sv
> +    s_sel_onehot[async_sel_i] =1'b1;
```suggestion
    s_sel_onehot[async_sel_i] = 1'b1;
```

2022-12-15 13:44 UTC, niwis commented on test/clk_mux_glitch_free_tb.sv
> +    automatic realtime last_low_pulse_duration = 0ns;
```suggestion
    automatic realtime last_low_pulse_duration  = 0ns;
```

2022-12-15 13:44 UTC, niwis commented on src/clk_mux_glitch_free.sv
> +
```suggestion
```

2022-12-15 14:08 UTC, meggiman commented
I just updated the README, FusoSoC core fiel and the src_files.yml. Should be ready now.

2022-12-15 16:59 UTC, niwis approved these changes
Perfect, thanks a lot!

2022-12-15 17:02 UTC, merged