Add shift_register_gated
pulp-platform/common_cells pull request #170
Opened 2023-02-22 17:09 UTC by qian-gu

A shift register with clock gating

2023-02-23 11:25 UTC, niwis requested changes
Thank you @qian-gu for this PR. To avoid code fragmentation, could you adapt [shift_reg](https://github.com/pulp-platform/common_cells/blob/master/src/shift_reg.sv) such that it instantiates this module, tying `valid_i` to `1'b1` and leaving `valid_o` open? Furthermore, could you update the following files with this module:
- `Bender.yml`
- `README.md`
- `src_files.yml`

2023-02-23 14:50 UTC, qian-gu commented on src/shift_reg_gated.sv
> +`default_nettype none
This directive is added to ensure all internal variables are declared explicitly by designer. I will remove it to keep consistent with other modules.

2023-02-27 15:24 UTC, qian-gu commented
update commits have been pushed, but the CI command

> git remote add gitlab ***iis-git.ee.ethz.ch/github-mirror/common_cells
> git push --force --mirror gitlab

gives an error message:

> remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password.

2023-04-14 14:08 UTC, niwis approved these changes
Thanks a lot! The CI is failing since you don't have access to the required github secrets... we're working on a solution for future PRs.

2023-04-14 14:08 UTC, merged