Simplify popcount and add proper support for all input widths
pulp-platform/common_cells pull request #188
Opened 2023-05-24 12:16 UTC by meggiman

The popcount implementation so far used a recursive implementation using a binary adder tree. However, experiments using reasonably modern synthesis tools show that the logic optimization heuristics achieve the same or better results in less compilation time when the popcount logic is described in a flat for loop instead of nested modules.
While simplifying the popcount implementation, this change also fixes #187

2023-05-24 13:18 UTC, bluewww approved these changes
LGTM!

2023-05-29 12:27 UTC, niwis requested changes
Thanks a lot! Just one typo from my side

2023-05-29 12:27 UTC, niwis commented on src/popcount.sv
> +// This module usded tobe implemented using a binary added tree. However,
fix typo
```suggestion
// This module used to be implemented using a binary added tree. However,
```

2023-05-29 12:27 UTC, niwis commented on test/popcount_tb.sv
> +   logic  popcount_w1;
fix alignment
```suggestion
   logic popcount_w1;
```

2023-05-30 18:06 UTC, niwis approved these changes

2023-05-30 18:07 UTC, merged