Add credit_counter
pulp-platform/common_cells pull request #225
Opened 2024-07-17 15:32 UTC by micprog

2024-07-17 18:34 UTC, paulsc96 approved these changes

2024-07-18 09:19 UTC, niwis requested changes
Hi @micprog, thanks for upstreaming this! I just have one minor suggestion

2024-07-18 09:19 UTC, niwis commented on src/credit_counter.sv
> +  `FFLARNC(credit_q, credit_d, credit_load, credit_init_i, InitNumCredits, clk_i, rst_ni)
Can we use `FFARNC` instead of tying the load enable?

2024-07-18 12:02 UTC, niwis approved these changes

2024-07-18 12:03 UTC, merged