Replace all asserts & assumes with macros from `assertions.svh`
pulp-platform/common_cells pull request #233
Opened 2024-09-18 13:38 UTC by michael-platzer

This PR replaces all assertions (and assumes) in the common cells sources with macros from [`assertions.svh`](https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/assertions.svh).

Additionally, the `assertions.svh` itself is modified as follows:
- Some defines (such as the guard block at the start of the header) are renamed for consistency and to avoid name collisions in the same style as in [`registers.svh`](https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/registers.svh).
- The `` `ifndef VERILATOR`` is removed because Verilator has supported assertions for a while now.
- An option to override any of the default defines that cause assertions to be turned off (such as `SYNTHESIS`) is added (so even if a tool defines, e.g., `SYNTHESIS`, it still has the option to forcefully enable assertions by also defining `ASSERTS_OVERRIDE_ON` now — yes, there are tools out there that require that :roll_eyes:).
- Helper macros are undefined at the end of the file (a comment did claim that this was already the case, but it was not).
- An optional extra argument is added to all assertions macros, which allows to specify a custom error message to be displayed when the assertion fails. For backwards compatibility, this extra argument is added at the end and defaults to  `""`.

In order to replace all the assertions in the sources while avoiding typos and other oversights as best as possible, I have replaced almost all of them using sed commands. The specific commands used for each change are part of the respective commit messages.

Some noteworthy subtle changes that go along with this move:
- The macros in `assertions.svh` require that all assertions have a name, so I added one for all those who did not have one (and I tried to hard to keep them consistent).
- So far, assertions used a mix of `$fatal`, `$error`, and sometimes `$warning` to report failing assertions. The macros in `assertions.svh` universally use `$error` and all instances of `$fatal` are now changed to `$error`. I reviewed all those that used `$warning` but since they all appear to be pretty critical issues as well, they now also use the macros which report an `$error` (the affected files are `src/addr_decode_dync.sv`, `src/cdc_fifo_gray_clearable.sv`, `src/multiaddr_decode.sv`, and `src/spill_register_flushable.sv`, so the authors of these @WRoenninger, @fabianschuiki, @zarubaf, @meggiman, and @colluca might want to take a look).
- Assertions that were previously declared as `assert initial` or `assert final` are now immediate assertions in a `begin initial` or `begin final` block, respectively.
- `src/rr_arb_tree.sv`, `src/stream_omega_net.sv`, and `src/stream_xbar.sv` previously used a default disable (e.g., `default disable iff (~rst_ni);`), which btw is also not supported by Verilator. Each assertion macro has an `iff !rst_ni` instead, so I removed those.

Also, the following files make use of assertions in a pretty advanced/adventurous way (which btw also causes Verilator 5.018 to fail as reported in #229):
- `src/addr_decode_dync.sv`: Includes a huge `always` block with `assume`s all over the place.
- `src/multiaddr_decode.sv`: Again an `always` block with an `assume` in it.

I'd like to ask the respective authors (@WRoenninger and @colluca) to review the changes to these files (you are of course welcome to review changes to the other files as well).

Merging this PR closes #232.

2024-09-18 13:43 UTC, colluca commented
@michael-platzer thanks for the PR :)

I will not be able to review this before Monday, but I will definitely have a look then.

2024-09-24 06:25 UTC, michael-platzer commented
I reckon that this is a pretty large PR. @niwis Would you rather have me split this into multiple smaller PRs? Perhaps starting with the changes to `assertions.svh` only?

2024-09-26 09:45 UTC, colluca requested changes
Thanks for the PR @michael-platzer!

It looks good to me for the most part.

One thing I would perhaps change, is to move all `include` statements at the beginning of the files, rather than within the modules. I believe this is more consistent with other include statements and better aligned with one's expectation on where to find included files. Also, for files defining multiple modules e.g. `cdc_2phase_clearable` this would mean we only need to include it once.

Could we also move `COMMON_CELLS_ASSERTS_OFF` to `assertions.svh` for consistency? As of now, some but not all assertions would be disabled, which I think would go against expectation.

Finally, in the PR description (and later in the changelog) I would mention that some assertions which did not define a `disable iff` condition now do after aligning them to use the `ASSERT` macro, and I would list the files affected by this change (e.g. `stream_to_mem.sv`).

2024-09-26 09:45 UTC, colluca commented on src/stream_omega_net.sv
> +    `ASSERT_INIT(bit_sclicing_broken, $clog2(NumLanes) % SelW == 0, "Bit slicing of the internal selection signal is broken.")
Typo in `bit_sclicing_broken`

2024-09-27 13:46 UTC, phsauter requested changes

2024-09-27 13:46 UTC, phsauter commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
This should be left in to turn off only common cells assertions (and for consistency).

2024-09-27 13:46 UTC, phsauter commented on src/onehot_to_bin.sv
> +    `ASSERT_FINAL(more_than_2_bits, $onehot0(onehot), "[onehot_to_bin] More than two bit set in the one-hot signal")
I would remove the [onehot_to_bin] since the final message will already be [ASSERT FAILED] [instance] more_than2_bits ... (file:line)

2024-09-27 13:46 UTC, phsauter commented on src/rr_arb_tree.sv
> +                            ready.")
nitpick: maybe just move the entire message to the next line

2024-09-27 13:46 UTC, phsauter commented on src/rr_arb_tree.sv
> +                            enabled.")
nitpick: maybe just move the entire message to the next line

2024-09-27 13:46 UTC, phsauter commented on src/mem_to_banks_detailed.sv
> +               "Data width must be a power of two!")
Seems like an insane way to check if it is power of 2. The one used in eg stream_omega_net.sv is a lot saner.

2024-09-27 14:43 UTC, colluca commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
What do you think about moving `COMMON_CELLS_ASSERTS_OFF` to `assertions.svh` and have it act globally on all assertions?

2024-09-27 14:45 UTC, phsauter commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
In principle I am not against it but to me the purpose of COMMON_CELLS_ASSERTS_OFF is to turn off the asserts only in the common cells. Other IPs might still want to use the provided macros though.

But maybe I misunderstood the point of COMMON_CELLS_ASSERTS_OFF.

2024-09-27 15:05 UTC, colluca commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
What you say makes sense.

Perhaps what we could have in `assertions.svh` is something like the following:
```
`ifndef COMMON_CELLS
`ifdef COMMON_CELLS_ASSERTS_OFF
`undef COMMON_CELLS_ASSERTS_OFF
`endif
`endif
```

Where we could define `COMMON_CELLS` e.g. using Bender, for the `common_cells` source groups only https://github.com/pulp-platform/bender?tab=readme-ov-file#sources.

Technically, users could even achieve the goal you mention without the guard above, by just defining  `COMMON_CELLS_ASSERTS_OFF` on the commands compiling `common_cells` source groups only, but I guess this might not be straightforward to do.

Alternatively, as far as I'm concerned, we could also just cope with a little bit of boilerplate code, and surround all assertions in `common_cells` with the `COMMON_CELLS_ASSERTS_OFF` guard, but I think this PR would be a good moment to do so.

2024-09-27 17:11 UTC, phsauter commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
I think thats a good approach, maybe we could plan for an automatic define that is added to files of a package, similar to how Bender will automatically add `TARGET_*` defines.  
So something like `PACKAGE_COMMON_CELLS` or `BENDER_COMMON_CELLS`.

2024-09-30 06:52 UTC, michael-platzer commented on include/common_cells/assertions.svh
> +  $fatal(1, "[ASSERT FAILED] [%m] %s (%s:%0d)", __name, `__FILE__, `__LINE__); \
Indeed. Apologies, that change was not meant to make it into the PR :see_no_evil:

2024-09-30 06:52 UTC, michael-platzer commented on src/stream_omega_net.sv
> +    `ASSERT_INIT(bit_sclicing_broken, $clog2(NumLanes) % SelW == 0, "Bit slicing of the internal selection signal is broken.")
Thanks for spotting!

2024-09-30 06:52 UTC, michael-platzer commented on src/onehot_to_bin.sv
> +    `ASSERT_FINAL(more_than_2_bits, $onehot0(onehot), "[onehot_to_bin] More than two bit set in the one-hot signal")
Done!

2024-09-30 06:53 UTC, michael-platzer commented on src/rr_arb_tree.sv
> +                            ready.")
Done and fixed all the line-length lint warnings.

2024-09-30 06:53 UTC, michael-platzer commented on src/rr_arb_tree.sv
> +                            enabled.")
Done and fixed all the line-length lint warnings.

2024-09-30 06:53 UTC, michael-platzer commented on src/mem_to_banks_detailed.sv
> +               "Data width must be a power of two!")
Good point, changed it.

2024-09-30 06:57 UTC, michael-platzer commented
Thanks a lot @colluca and @phsauter for the reviews!

> One thing I would perhaps change, is to move all `include` statements at the beginning of the files, rather than within the modules. I believe this is more consistent with other include statements and better aligned with one's expectation on where to find included files. Also, for files defining multiple modules e.g. `cdc_2phase_clearable` this would mean we only need to include it once.

Agree, for the assertion macros this makes more sense, since they are intended to be defined globally anyways.

> Could we also move `COMMON_CELLS_ASSERTS_OFF` to `assertions.svh` for consistency? As of now, some but not all assertions would be disabled, which I think would go against expectation.

We could, but IMHO that is not consistent and would defeat the purpose to disable assertions in the `common_cells` sources only while allowing the assertion macros to be used in other places as well. See my comments above.

> Finally, in the PR description (and later in the changelog) I would mention that some assertions which did not define a `disable iff` condition now do after aligning them to use the `ASSERT` macro, and I would list the files affected by this change (e.g. `stream_to_mem.sv`).

Good point, will add that.

2024-09-30 08:42 UTC, colluca commented on src/addr_decode_dync.sv
> -  `ifndef COMMON_CELLS_ASSERTS_OFF
We can keep it as is for now, and eventually address it in a separate PR.

2024-09-30 08:45 UTC, colluca approved these changes

2024-09-30 11:23 UTC, michael-platzer commented
Please note that `addr_decode_dync.sv` fails to elaborate with the newest Verilator release 5.028 because of issues with the assertion constructs that are unrelated to the changes in this PR. See https://github.com/pulp-platform/common_cells/pull/229#issuecomment-2382908002

2024-09-30 12:20 UTC, phsauter approved these changes

2024-10-03 06:48 UTC, niwis approved these changes
Thank you very much @michael-platzer! Also @colluca and @phsauter for your thorough reviews! As far as I can tell, all changes are backwards-compatible. In particular, no new `fatal`s were introduced. Could you confirm? In that case, I think this does not require a major release. Please let me know if you have any objections.

2024-10-03 06:57 UTC, michael-platzer commented
> As far as I can tell, all changes are backwards-compatible.

To the best of my knowledge, they should be.

> In particular, no new `fatal`s were introduced.

That, I can confirm with certainty. Some `$fatal`s have been converted to `$error`s but there are no new `$fatal`s for sure.

2024-10-04 01:03 UTC, merged