[HW]: Add mem_multibanked_pwrgate for correct power management
pulp-platform/common_cells pull request #246
Opened 2024-10-28 09:35 UTC by Lore0599

# Power Gated MutliBanked Memory
This PR introduces the `mem_multibank_pwrgate.sv`module.

## Goal
When designing power-aware systems, memory macro cells often include control signals dedicated to powering down/up the bank and entering retention mode. Additionally, when each bank in the memory is made of different cuts, the power control signals must be properly managed to maintain the memory’s interleaved addressing scheme..

## Addition:
- `mem_multibank_pwrgate.sv`: In a memory system with multiple banks and applied power strategies, each bank must be correctly managed to avoid disruptions in memory interleaving. For memories with multiple cuts and interleaved banks, it is important to ensure that power signals do not disrupt the internal bank interleaving. This module is responsible for correctly addressing each internal bank and connecting the appropriate power control signals.
- `mem_multibank_pwrgate_tb.sv`: A testbench to verify the correct addressing functionality of the implemented module.

2024-10-31 07:03 UTC, niwis requested changes
Hi @Lore0599, thank you for the contribution! I have one general question: would there be a point in generalising the module further? Specifically, I don't see the direct relevance of the `deepsleep` and `powergate` signals in the module implementation. They are "just" packed into the `impl_i` ports of the `tc_sram`s. Would it make sense to expose the `impl_i` ports directly (instead of `deepsleep_i` and `powergate_i`) to make this module independent of the technology, perhaps even of the use case (power management), and pack them outside the module?

Other than that, I have added a couple of nitpicks inline. Furthermore, I would like to ask you the following:
- [ ] add the new testbench to [.gitlab-ci.yml](https://github.com/pulp-platform/common_cells/blob/master/.gitlab-ci.yml)
- [ ] add a module description in the [README.md](https://github.com/pulp-platform/common_cells/blob/master/README.md)
- [ ] add the new source files to [common_cells.core](https://github.com/pulp-platform/common_cells/blob/master/common_cells.core)
- [ ] fix the lint errors in the CI.

Thanks a lot!

2024-10-31 08:06 UTC, Lore0599 commented
Hi @niwis, thank you for your comments. I'll implement all of them ASAP.
Just one note regarding the `impl_i` port: this module is intended to be used with a Power Management Unit (PMU). The `deepsleep_i` and `powergated_i` signals will be driven by the PMU. The connection can be made through the SystemVerilog system description, but since the module’s goal is to enable power-aware simulation, the ports are likely to be floating initially and then properly connected using the UPF system description.
I don't have much experience with UPF, but over the past month, I discovered that complex types like structs can pose challenges, as UPF seems unable to recognize them effectively. This is the main reason I chose to keep these signals flattened at the interface.
That said, I can implement all your suggestions and try using the impl_i at the interface to see if UPF can handle it :).

2024-10-31 08:13 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      ) : 32'd1;
done

2024-10-31 08:16 UTC, niwis commented
I see. Otherwise, perhaps you could add another wrapping layer that packs the signals locally? I'm just thinking that feeding through the implementation ports might increase the reusability of this module.

2024-10-31 08:27 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      logic  [     NumPorts-1:0][BankSelWidth-1:0]                             bank_sel;
done

2024-10-31 08:35 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      logic [NumPorts-1:0][Latency-1:0][BankSelWidth-1:0] out_mux_sel_d, out_mux_sel_q;
You're right. Strange that the testbench didn't complain about it, because `Latency == 0` is tested in [here](https://github.com/pulp-platform/common_cells/blob/44a66c77461d81a66fa53a68921b4107c573a26f/test/simulate.sh#L27)

2024-10-31 08:53 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +         $fatal("Logic Bank size is not a power of two: UNSUPPORTED ");
done

2024-10-31 08:57 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +`endif
In this case, I don’t want to trigger an `$error`; I only want to generate a `$warning` to make the user aware that these signals are not connected. This should serve as a helpful insight for users working with UPF.
I believe that if I use `ASSERT_INIT`, which relies on `ASSERT_RPT` leaving the ports unconnected will result in an error. Is there a way to only print a warning instead?

2024-10-31 10:00 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +            end
done

2024-10-31 10:38 UTC, Lore0599 commented
@niwis Regarding the CI linting failure, the source of the error is the missing type specification for some parameters at the interface (https://github.com/pulp-platform/common_cells/blob/f374a5b468968cf014d18bc5e7f26d6e378a101b/src/mem_multibank_pwrgate.sv#L28). These parameters are of `string` type, and similarly, in the `tc_sram` module (https://github.com/pulp-platform/tech_cells_generic/blob/7968dd6e6180df2c644636bc6d2908a49f2190cf/src/rtl/tc_sram.sv#L62)  their type is also unspecified. 
Would you prefer that I explicitly specify the type as string, or should we consider suppressing the linting error as done [**here**](https://github.com/chipsalliance/verible/issues/167#issuecomment-581066914)? On [**this forum**](https://github.com/chipsalliance/verible/issues/167#issuecomment-581105532) it appears that not specifying the string type can serve as a workaround for compatibility with tools like Vivado.

2024-11-01 01:12 UTC, niwis commented on src/mem_multibank_pwrgate.sv
> +      logic  [     NumPorts-1:0][BankSelWidth-1:0]                             bank_sel;
I see you fixed `bank_sel`, but same for `*_cut`

2024-11-01 01:16 UTC, niwis commented on src/mem_multibank_pwrgate.sv
> +`endif
fine by me. Seems like this is also done elsewhere in the repo

2024-11-01 01:30 UTC, niwis requested changes

2024-11-01 01:30 UTC, niwis commented on src/mem_multibank_pwrgate.sv
> +      $fatal("Error: %d logic banks are not supported", NumLogicBanks);
Sorry, I previously overlooked this. Can you also change this to an assertion macro?

2024-11-01 01:30 UTC, niwis commented on src/mem_multibank_pwrgate.sv
> +            // end
I think this block can be removed, right?

2024-11-01 01:32 UTC, niwis commented
> Would you prefer that I explicitly specify the type as string, or should we consider suppressing the linting error as done [**here**](https://github.com/chipsalliance/verible/issues/167#issuecomment-581066914)? On [**this forum**](https://github.com/chipsalliance/verible/issues/167#issuecomment-581105532) it appears that not specifying the string type can serve as a workaround for compatibility with tools like Vivado.

Good point. You can add a waiver for this line here: https://github.com/pulp-platform/common_cells/blob/554ebbcdd3d4d55f9d94dbee47f957af93a835a8/lint/common_cells.style.waiver#L4-L6

2024-11-01 06:53 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      logic  [     NumPorts-1:0][BankSelWidth-1:0]                             bank_sel;
sorry, it was an issue of my text editor.

2024-11-01 06:54 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +            // end
done

2024-11-01 06:57 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      $fatal("Error: %d logic banks are not supported", NumLogicBanks);
done

2024-11-01 10:49 UTC, Lore0599 commented on src/mem_multibank_pwrgate.sv
> +      $fatal("Error: %d logic banks are not supported", NumLogicBanks);
@niwis (https://github.com/pulp-platform/common_cells/pull/246#discussion_r1824097198)

2024-12-04 06:40 UTC, niwis commented on src/mem_multibank_pwrgate.sv
> +         $fatal("Logic Bank size is not a power of two: UNSUPPORTED ");
I think you're right. This works for me :)

2024-12-04 06:43 UTC, niwis commented
Hi @Lore0599, sorry for the long silence. Have you had any success with propagating the `impl_i` ports?

2025-05-21 15:44 UTC, sermazz commented on src/mem_multibank_pwrgate.sv
> +    parameter int unsigned NumLogicBanks = 32'd1, // Logic bank for Power Management
@Lore0599 Let's double check that the terms LogicBanks/PhysicalBanks have correct semantics

2026-05-07 11:31 UTC, phsauter commented
I am quite strongly opposed to merge this.  
I do not think it is a good idea to have things that are so technology dependent like power gating or wrappers around SRAMs in the common cells.  
In general we should strive to keep the modules here more technology independent where possible. Of course sometimes it is required (eg for clocking modules) but otherwise I think we should strongly prefer building adapters and self-contained units instead of wrapping technology dependent things like SRAMs.  
I would not be opposed to something that just makes it easier to connect to memories and can help manage though even then I question if this should be in common_cells. To me this goes in a similar direction as https://github.com/pulp-platform/tech_cells_generic/issues/40 and should probably be handled in the tech_cells_generic instead.

I will close this issue but keep the branch (renamed to archive/pwr-mbank-mem) and if you are still interested in something like this, feel free to discuss here or contact me.

2026-05-07 11:31 UTC, closed without merging